const data = [
  {
    "Marca": "MERCEDES",
    "Modello": "SMART FOR TWO INTERM.",
    "C-2.32ECO": "JUSTO",
    "C2.32CONFORT": "JUSTO",
    "C2.32SyncECO": "JUSTO",
    "C2.32SyncCONFORT": "JUSTO",
    "C-3.5 B.TRIP": "NO",
    "C-3,5 XL BASE A 3M": "NO",
    "C3,5Sync  BR. TRIPLE": "NO",
    "C3,5Sync XL 3M": "NO",
    "C-4": "NO",
    "C-4 XL BASE A 3M": "NO",
    "C-4 Sync": "NO",
    "C4Sync XL 3M": "NO",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "MERCEDES",
    "Modello": "SMART FOR TWO 2015",
    "C-2.32ECO": "JUSTO",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "JUSTO",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "JUSTO",
    "C-3,5 XL BASE A 3M": "NO",
    "C3,5Sync  BR. TRIPLE": "JUSTO",
    "C3,5Sync XL 3M": "NO",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "NO",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "NO",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "MERCEDES",
    "Modello": "SMART FOR TWO ANT.",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "JUSTO",
    "C-3,5 XL BASE A 3M": "NO",
    "C3,5Sync  BR. TRIPLE": "JUSTO",
    "C3,5Sync XL 3M": "NO",
    "C-4": "JUSTO",
    "C-4 XL BASE A 3M": "NO",
    "C-4 Sync": "JUSTO",
    "C4Sync XL 3M": "NO",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "RENAULT",
    "Modello": "CLIO GRAN TOUR",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "JUSTO",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "JUSTO",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "JUSTO",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "JUSTO",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "RENAULT",
    "Modello": "MODUS",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "JUSTO",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "JUSTO",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "JUSTO",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "JUSTO",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "RENAULT",
    "Modello": "CLIO NUEVO",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "JUSTO",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "JUSTO",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "JUSTO",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "JUSTO",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "TOYOTA",
    "Modello": "IQ",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "JUSTO",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "JUSTO",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "JUSTO",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "JUSTO",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "LANCIA",
    "Modello": "YPSILON",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "JUSTO",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "JUSTO",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "JUSTO",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "JUSTO",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "FIAT",
    "Modello": "PUNTO",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "RENAULT",
    "Modello": "MEGANE CORTO",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "TATA",
    "Modello": "INDIGO",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "LANCIA",
    "Modello": "MUSA",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "MAZDA",
    "Modello": "2",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "RENAULT",
    "Modello": "MEGANE",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "RENAULT",
    "Modello": "MEGANE SPORT TOURER",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "NISSAN",
    "Modello": "MICRA",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "NISSAN",
    "Modello": "QASHQAI",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "TOYOTA",
    "Modello": "RAV 4",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "MERCEDES",
    "Modello": "COOPER D",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "OPEL",
    "Modello": "CORSA",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "ROVER",
    "Modello": "MINI CLUBMAN",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "BMW",
    "Modello": "X3",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "LANCIA",
    "Modello": "DELTA",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "MAZDA",
    "Modello": "CX-7",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "BMW",
    "Modello": "120D",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "BMW",
    "Modello": "SERIE3",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "BMW",
    "Modello": "335",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "BMW",
    "Modello": "320",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "BMW",
    "Modello": "330XD (E46)",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "NISSAN",
    "Modello": "TIIDA",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "JUSTO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "FORD",
    "Modello": "FOCUS",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "FORD",
    "Modello": "FIESTA",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "JUSTO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "MAZDA",
    "Modello": "5",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "TOYOTA",
    "Modello": "YARIS",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "TOYOTA",
    "Modello": "AURIS",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "MITSUBISHI",
    "Modello": "COLT",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "JUSTO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "SKODA",
    "Modello": "FABIA",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "NISSAN",
    "Modello": "NOTE",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "JUSTO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "MERCEDES",
    "Modello": "CLASE A",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "JUSTO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "TATA",
    "Modello": "INIDICA",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "FERRARI",
    "Modello": "F430",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "MAZDA",
    "Modello": "3",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "OPEL",
    "Modello": "VECTRA",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "NISSAN",
    "Modello": "X-TRAIL",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "JUSTO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "JUSTO",
    "C5,5SynC Br. Bajos 3M": "JUSTO"
  },
  {
    "Marca": "ALFA",
    "Modello": "147",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "LAND ROVER",
    "Modello": "FREELANDER 2",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "JUSTO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "JUSTO",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "MAZDA",
    "Modello": "6",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "JUSTO",
    "C5,5SynC Br. Bajos 3M": "JUSTO"
  },
  {
    "Marca": "OPEL",
    "Modello": "ASTRA",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "ALFA",
    "Modello": "159",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "JUSTO",
    "C5,5SynC Br. Bajos 3M": "JUSTO"
  },
  {
    "Marca": "MICROCAR",
    "Modello": "MICROCAR\"CELES\"",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "JUSTO",
    "C5,5 BRAZOS VW": "JUSTO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "VOLKSWAGEN",
    "Modello": "GOLF",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "JUSTO",
    "C5,5SynC Br. Bajos 3M": "JUSTO"
  },
  {
    "Marca": "AUDI",
    "Modello": "A3",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "SEAT",
    "Modello": "IBIZA NUEVO",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "JUSTO"
  },
  {
    "Marca": "SEAT",
    "Modello": "CORDOBA",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "JUSTO"
  },
  {
    "Marca": "CITROEN",
    "Modello": "C3",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "JUSTO"
  },
  {
    "Marca": "VOLKSWAGEN",
    "Modello": "GOLF R-32",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "JUSTO",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "SEAT",
    "Modello": "LEON FR",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "JUSTO",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "SEAT",
    "Modello": "ALTEA XL",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "JUSTO",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "TOYOTA",
    "Modello": "AVENSIS",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "JUSTO",
    "C5,5SynC Br. Bajos 3M": "JUSTO"
  },
  {
    "Marca": "VOLKSWAGEN",
    "Modello": "SCIROCCO",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "JUSTO",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "FIAT",
    "Modello": "CROMA RANCHERA",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "JUSTO",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "HONDA",
    "Modello": "CIVIC",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "RENAULT",
    "Modello": "SCENIC",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "SUBARU",
    "Modello": "JUSTY",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "CITROEN",
    "Modello": "C4",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "JUSTO",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "PEUGEOT",
    "Modello": "308",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "JUSTO",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "AUDI",
    "Modello": "Q5",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "JUSTO",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "JUSTO",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "CITROEN",
    "Modello": "C4 PICASSO",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "PEUGEOT",
    "Modello": "207",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "AUDI",
    "Modello": "A4 NUEVO",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "HYUNDAI",
    "Modello": "SANAFE",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "HYUNDAI",
    "Modello": "I10",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "JUSTO",
    "C5SyncWAGON 3M": "JUSTO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "JUSTO",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "MERCEDES",
    "Modello": "CLASE C",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "VOLKSWAGEN",
    "Modello": "PASSAT",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "HONDA",
    "Modello": "JAZZ",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "RENAULT",
    "Modello": "CLIO",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "JUSTO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "JUSTO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "SUBARU",
    "Modello": "IMPREZA",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "FORD",
    "Modello": "TOURNEO",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "HYUNDAI",
    "Modello": "I30",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "FIAT",
    "Modello": "BRAVO",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "JUSTO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "HONDA",
    "Modello": "ACCORD",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "SKODA",
    "Modello": "ROOMSTER",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "HONDA",
    "Modello": "CR-V",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "MITSUBISHI",
    "Modello": "LANCER",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "PEUGEOT",
    "Modello": "407",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "MERCEDES",
    "Modello": "SMART FOR FOUR 2015",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "JUSTO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "BMW",
    "Modello": "525",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "FORD",
    "Modello": "S-MAX",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "BMW",
    "Modello": "530 NUEVA SERIE",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "JUSTO",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "FORD",
    "Modello": "MONDEO",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "RENAULT",
    "Modello": "ESPACE",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "CITROEN",
    "Modello": "C5",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "JAGUAR",
    "Modello": "XTYPE",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "JUSTO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "JUSTO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "HYUNDAI",
    "Modello": "SONATA",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "JUSTO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "JUSTO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "MERCEDES",
    "Modello": "CLASE E KOMPRESSOR",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "CITROEN",
    "Modello": "BERLINGO",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "PEUGEOT",
    "Modello": "PARTNER",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "FORD",
    "Modello": "K",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "SI",
    "C5SyncWAGON 3M": "SI",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "SKODA",
    "Modello": "SUPERB",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "SKODA",
    "Modello": "OCTAVIA",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "JUSTO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "JUSTO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "TOYOTA",
    "Modello": "COROLLA",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "SI",
    "C5SyncWAGON 3M": "SI",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "TOYOTA",
    "Modello": "PRIUS",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "JUSTO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "JUSTO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "BMW",
    "Modello": "X5",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "NISSAN",
    "Modello": "KUBISTAR",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "SI",
    "C5SyncWAGON 3M": "SI",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "OPEL",
    "Modello": "ZAFIRA",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "SI",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "RENAULT",
    "Modello": "KANGOO",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "SI",
    "C5SyncWAGON 3M": "SI",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "MERCEDES",
    "Modello": "CLASE R",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "NO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "PEUGEOT",
    "Modello": "607",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "SI",
    "C5SyncWAGON 3M": "SI",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "MERCEDES",
    "Modello": "CLASE M",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "NO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "JUSTO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "RENAULT",
    "Modello": "LAGUNA NUEVO",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "SI",
    "C5SyncWAGON 3M": "SI",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "FERRARI",
    "Modello": "355",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "SI",
    "C5SyncWAGON 3M": "SI",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "RENAULT",
    "Modello": "VELSANTIS",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "SI",
    "C5SyncWAGON 3M": "SI",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "AUDI",
    "Modello": "A8",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "SI",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "VOLKSWAGEN",
    "Modello": "TOUAREG",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "SI",
    "C5SyncWAGON 3M": "SI",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "CITROEN",
    "Modello": "C8",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "JUSTO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "FIAT",
    "Modello": "ULYSE MONOVOLUMEN",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "JUSTO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "LANCIA",
    "Modello": "PMEDRA",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "JUSTO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "PEUGEOT",
    "Modello": "807",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "NO",
    "C5SyncWAGON 3M": "JUSTO",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "CITROEN",
    "Modello": "JUMPY",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "SI",
    "C5SyncWAGON 3M": "SI",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "MERCEDES",
    "Modello": "CLASE S",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "SI",
    "C5SyncWAGON 3M": "SI",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "PEUGEOT",
    "Modello": "EXPERT",
    "C-2.32ECO": "SI",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "SI",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "SI",
    "C5SyncWAGON 3M": "SI",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "MERCEDES",
    "Modello": "SPRINTER",
    "C-2.32ECO": "NO",
    "C2.32CONFORT": "NO",
    "C2.32SyncECO": "NO",
    "C2.32SyncCONFORT": "NO",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "SI",
    "C5SyncWAGON 3M": "SI",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "BMW",
    "Modello": "G12",
    "C-2.32ECO": "JUSTO",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "JUSTO",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "SI",
    "C5SyncWAGON 3M": "SI",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "MERCEDES",
    "Modello": "VITO",
    "C-2.32ECO": "JUSTO",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "JUSTO",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "SI",
    "C5SyncWAGON 3M": "SI",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "NISSAN",
    "Modello": "PRIMASTAR",
    "C-2.32ECO": "JUSTO",
    "C2.32CONFORT": "SI",
    "C2.32SyncECO": "JUSTO",
    "C2.32SyncCONFORT": "SI",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "SI",
    "C5SyncWAGON 3M": "SI",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "VOLKSWAGEN",
    "Modello": "CRAFTER DOKA L3 ZWILLING H-L",
    "C-2.32ECO": "NO",
    "C2.32CONFORT": "NO",
    "C2.32SyncECO": "NO",
    "C2.32SyncCONFORT": "NO",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "SI",
    "C5SyncWAGON 3M": "SI",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "VOLKSWAGEN",
    "Modello": "CRAFTER F-Q y EIKA F-Q L3",
    "C-2.32ECO": "NO",
    "C2.32CONFORT": "NO",
    "C2.32SyncECO": "NO",
    "C2.32SyncCONFORT": "NO",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "SI",
    "C5SyncWAGON 3M": "SI",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "VOLKSWAGEN",
    "Modello": "CRAFTER L3 ZWILLING",
    "C-2.32ECO": "NO",
    "C2.32CONFORT": "NO",
    "C2.32SyncECO": "NO",
    "C2.32SyncCONFORT": "NO",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "JUSTO",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "JUSTO",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "JUSTO",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "JUSTO",
    "C-5WAGON": "SI",
    "C5SyncWAGON 3M": "SI",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "VOLKSWAGEN",
    "Modello": "CRAFTER L3 F-Q + 4X4",
    "C-2.32ECO": "NO",
    "C2.32CONFORT": "NO",
    "C2.32SyncECO": "NO",
    "C2.32SyncCONFORT": "NO",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "SI",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "SI",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "SI",
    "C5SyncWAGON 3M": "SI",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "RENAULT",
    "Modello": "TRAFFIC",
    "C-2.32ECO": "NO",
    "C2.32CONFORT": "NO",
    "C2.32SyncECO": "NO",
    "C2.32SyncCONFORT": "NO",
    "C-3.5 B.TRIP": "SI",
    "C-3,5 XL BASE A 3M": "JUSTO",
    "C3,5Sync  BR. TRIPLE": "SI",
    "C3,5Sync XL 3M": "JUSTO",
    "C-4": "SI",
    "C-4 XL BASE A 3M": "SI",
    "C-4 Sync": "SI",
    "C4Sync XL 3M": "SI",
    "C-5WAGON": "SI",
    "C5SyncWAGON 3M": "SI",
    "C-5,5 BRAZOS BAJOS": "SI",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "SI"
  },
  {
    "Marca": "VOLKSWAGEN",
    "Modello": "CRAFTER DOKA ZWILLING H/L L4 + FQ",
    "C-2.32ECO": "NO",
    "C2.32CONFORT": "NO",
    "C2.32SyncECO": "NO",
    "C2.32SyncCONFORT": "NO",
    "C-3.5 B.TRIP": "NO",
    "C-3,5 XL BASE A 3M": "NO",
    "C3,5Sync  BR. TRIPLE": "NO",
    "C3,5Sync XL 3M": "NO",
    "C-4": "NO",
    "C-4 XL BASE A 3M": "NO",
    "C-4 Sync": "NO",
    "C4Sync XL 3M": "NO",
    "C-5WAGON": "SI",
    "C5SyncWAGON 3M": "SI",
    "C-5,5 BRAZOS BAJOS": "JUSTO",
    "C5,5 BRAZOS VW": "JUSTO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "VOLKSWAGEN",
    "Modello": "CRAFTER EIKA F-Q L4",
    "C-2.32ECO": "NO",
    "C2.32CONFORT": "NO",
    "C2.32SyncECO": "NO",
    "C2.32SyncCONFORT": "NO",
    "C-3.5 B.TRIP": "NO",
    "C-3,5 XL BASE A 3M": "NO",
    "C3,5Sync  BR. TRIPLE": "NO",
    "C3,5Sync XL 3M": "NO",
    "C-4": "NO",
    "C-4 XL BASE A 3M": "NO",
    "C-4 Sync": "NO",
    "C4Sync XL 3M": "NO",
    "C-5WAGON": "SI",
    "C5SyncWAGON 3M": "SI",
    "C-5,5 BRAZOS BAJOS": "JUSTO",
    "C5,5 BRAZOS VW": "JUSTO",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "VOLKSWAGEN",
    "Modello": "CRAFTER L4 ZWILLING",
    "C-2.32ECO": "NO",
    "C2.32CONFORT": "NO",
    "C2.32SyncECO": "NO",
    "C2.32SyncCONFORT": "NO",
    "C-3.5 B.TRIP": "NO",
    "C-3,5 XL BASE A 3M": "NO",
    "C3,5Sync  BR. TRIPLE": "NO",
    "C3,5Sync XL 3M": "NO",
    "C-4": "NO",
    "C-4 XL BASE A 3M": "NO",
    "C-4 Sync": "NO",
    "C4Sync XL 3M": "NO",
    "C-5WAGON": "SI",
    "C5SyncWAGON 3M": "SI",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "NO",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "VOLKSWAGEN",
    "Modello": "CRAFTER L4 F/Q + 4X4",
    "C-2.32ECO": "NO",
    "C2.32CONFORT": "NO",
    "C2.32SyncECO": "NO",
    "C2.32SyncCONFORT": "NO",
    "C-3.5 B.TRIP": "NO",
    "C-3,5 XL BASE A 3M": "NO",
    "C3,5Sync  BR. TRIPLE": "NO",
    "C3,5Sync XL 3M": "NO",
    "C-4": "NO",
    "C-4 XL BASE A 3M": "NO",
    "C-4 Sync": "NO",
    "C4Sync XL 3M": "NO",
    "C-5WAGON": "SI",
    "C5SyncWAGON 3M": "SI",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "NO"
  },
  {
    "Marca": "VOLKSWAGEN",
    "Modello": "CRAFTER L5 F/Q + 4X4",
    "C-2.32ECO": "NO",
    "C2.32CONFORT": "NO",
    "C2.32SyncECO": "NO",
    "C2.32SyncCONFORT": "NO",
    "C-3.5 B.TRIP": "NO",
    "C-3,5 XL BASE A 3M": "NO",
    "C3,5Sync  BR. TRIPLE": "NO",
    "C3,5Sync XL 3M": "NO",
    "C-4": "NO",
    "C-4 XL BASE A 3M": "NO",
    "C-4 Sync": "NO",
    "C4Sync XL 3M": "NO",
    "C-5WAGON": "SI",
    "C5SyncWAGON 3M": "SI",
    "C-5,5 BRAZOS BAJOS": "NO",
    "C5,5 BRAZOS VW": "SI",
    "C5,5Sync BR. VW 3M": "SI",
    "C5,5SynC Br. Bajos 3M": "NO"
  }
];


function populateMarcaSelect() {
  const marcaSelect = document.getElementById("marcaSelect");
  const modelloSelect = document.getElementById("modelloSelect");
  let marcaSet = new Set();

  data.forEach(row => marcaSet.add(row.Marca));

  marcaSelect.innerHTML = '<option value="">Seleziona marca</option>';
  marcaSet.forEach(marca => {
    let option = document.createElement("option");
    option.value = marca;
    option.textContent = marca;
    marcaSelect.appendChild(option);
  });

  marcaSelect.addEventListener("change", () => {
    const selectedMarca = marcaSelect.value;
    modelloSelect.innerHTML = '<option value="">Seleziona modello</option>';
    let modelloSet = new Set();

    data.filter(d => d.Marca === selectedMarca).forEach(d => modelloSet.add(d.Modello));
    modelloSet.forEach(modello => {
      let option = document.createElement("option");
      option.value = modello;
      option.textContent = modello;
      modelloSelect.appendChild(option);
    });
  });

  modelloSelect.addEventListener("change", () => {
    const marca = marcaSelect.value;
    const modello = modelloSelect.value;
    const result = data.find(d => d.Marca === marca && d.Modello === modello);
    const resultsDiv = document.getElementById("results");
    resultsDiv.innerHTML = "";
    if (!result) {
      resultsDiv.innerHTML = "<p>Nessun risultato trovato.</p>";
      return;
    }
    let html = `<h3>${result.Marca} ${result.Modello}</h3><ul>`;
    Object.keys(result).forEach(k => {
      if (k !== "Marca" && k !== "Modello") {
        html += `<li>${k}: ${result[k]}</li>`;
      }
    });
    html += "</ul>";
    resultsDiv.innerHTML = html;
  });
}

window.addEventListener("DOMContentLoaded", populateMarcaSelect);
